package com.appywheel.callcodes;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;
import com.appywheel.callcodes.R;
import java.util.ArrayList;
import java.util.Arrays;

public class MainActivity extends ActionBarActivity {

    String[] items;
    ArrayList<String> listItems;
    ArrayAdapter<String> adapter;
    ListView listView;
    EditText editText;

    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        listView=(ListView)findViewById(R.id.listview);
        editText=(EditText)findViewById(R.id.txtsearch);
        initList();
        editText.addTextChangedListener(new TextWatcher() {

            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int
                    after) { }


            @Override
            public void onTextChanged(CharSequence s, int start, int before, int
                    count) {

                if (s.toString().equals("")) {
                    // reset listview
                    initList();
                } else {
                    // perform search
                    searchItem(s.toString());
                }
            }

            @Override
            public void afterTextChanged(Editable s) {
            }
        });
    }


    public void searchItem(String textToSearch){
        for(String item:items){
            if(!item.contains(textToSearch)){
                listItems.remove(item);
            }
        }
        adapter.notifyDataSetChanged();
    }

    public void initList(){
        items=new String[]{

                "Beta Version: AppyWheel Inc., (c) Shoaib Saadat",
                "A0 - Admission & Discharge - 3156/3157/3158/4089",
                "A3 Floor - Nursing Station - 3116/3117",
                "A3 Floor - Room  1 A - 3107",
                "A3 Floor - Room  1 B - 3108",
                "A3 Floor - Room  2 A - 3109",
                "A3 Floor - Room  2 B - 3110",
                "A3 Floor - Room  4 A - 3111",
                "A3 Floor - Room  5 A - 3112",
                "A3 Floor - Room  6 A - 3113",
                "A3 Floor - Room  7 A - 3114",
                "A4 Floor - Medical Officer Room - 3472",
                "A4 Floor - Nursing Station - 3140/3141",
                "A4 Floor - Room  1 A - 3131",
                "A4 Floor - Room  1 B - 3132",
                "A4 Floor - Room  11 A - 3987",
                "A4 Floor - Room  11 B - 3522",
                "A4 Floor - Room  12 A - 3118",
                "A4 Floor - Room  12 B - 3521",
                "A4 Floor - Room  13  - 3130",
                "A4 Floor - Room  14 - 3517",
                "A4 Floor - Room  2 A - 3133",
                "A4 Floor - Room  2 B - 3134",
                "A4 Floor - Room  4 A - 3135",
                "A4 Floor - Room  5 A - 3136",
                "A4 Floor - Room  6 A - 3137",
                "A4 Floor - Room  7 A - 3138",
                "Aamer Nabi Nur - Orthopedic Surgeon - 3850",
                "Aamer Nazir Ahmad - Medical Specialist - 3348",
                "Aamir Cheema - Quality Management - 4259",
                "Aamir Malik - Accounts & Finance - 3194",
                "Abdu Salam Khan - Emergency Medicine  - 3009",
                "Abdul Basit - MIS - 4296",
                "Abdul Hameed - Radiation Oncology - 3041",
                "Abdul Khaliq - Linen & Laundry - 3212",
                "Abdul Malik - Cardiac Surgeon Pediatric - 3236",
                "Abdul Rahim Khan - Nursing - 4268",
                "Abdul Wahab Yousafzai - Psychiatrist - 3986",
                "Abida Naqvi - Nursing - 3225",
                "Abida Zaheer - Linen & Laundry - 3523",
                "Advertisement - Shifa Publications - 3379",
                "Afshan Abbasi - Medical Staff Affairs - 4065",
                "Aftab Akhtar - Pulmonologist / Critical Care - 3198",
                "Afzaal Ahmed - Protocol & Regulatory - 3560/4567",
                "Ahmad Fawad Ali - Emergency Medicine  - 3009",
                "Ahmed Hassan - Accounts & Finance - 3029",
                "Ahsan Hameed - Dermatologist - 3851",
                "Ahsan Qazi - Radiology - 3722",
                "Air Conditioning A & B  Block - Material Works - 3145",
                "Air Conditioning E Block - Material Works - 3689",
                "Air Conditioning G Block - Material Works - 3628",
                "Ajmal Khanna - Operative Rooms E2 & F4 - 4392",
                "Alam Zeb - MIS - 4230",
                "Ali Afzal Sheikh - Material Management  - 4331",
                "Ali Amin - Tameer e Millat Foundation - 3180",
                "Allergy and Immunology - Reception - 3821/3825",
                "Altaf Hussain  - Admission & Discharge - 4353",
                "Aman Nawaz Khan - Radiologist - 4069",
                "Aman Nawaz Khan - Radiology - 3721",
                "Amer Awan - Ophthalmologist  - 3060",
                "Amer Farooq - Shifa News - 3341",
                "Amer Farooq - Shifa Publications - 3341",
                "Amir Cheema - Shifa Foundation - 4259",
                "Amjad Shehzad - Admission & Discharge - 4281",
                "Ammad Fahim - Clinical Research - 3984",
                "Amna Abbasi - Medical Staff Affairs - 3616",
                "Amna Batool - Dermatologist - 3851",
                "Anesthesia Office - Operative Rooms B2 - 3098",
                "Anesthesia Office - Operative Rooms E3 - 4157",
                "Angiography - Radiology - 3721",
                "Anjum Ehsan - G10 Hospital - 7474",
                "Anwar Ali Shah - Dental Surgeon - 3415",
                "Anwar Ul Haq - Pediatric Surgeon - 4410",
                "Aqeel Abbas - MIS - 4236",
                "Aqeel Mir - Purchase  - 3185",
                "Aqib Nazir Chaudhary - Accounts & Finance - 4302",
                "Arif Malik - Executive Management - 3953",
                "Arif Malik - General Surgeon - 3429",
                "Arif Malik - Medical Staff Affairs - 3953",
                "Arsalan Ahmad - Neurologist - 3297",
                "Arsla Naveed - Radiologist - 3731",
                "Asad Ali Saleem - Cardiologist - 3217",
                "Asfia Ur Rehman - MIS - 3960",
                "Asif - G10 Hospital - 7400",
                "Asif Masood - Radiation Oncologist - 4104",
                "Asif Mehmood Butt - MIS - 4096",
                "Asim Naveed - Accounts & Finance - 3424",
                "Asim Quraishi - Laboratory - 4116",
                "Asim Qureshi - Pathologist - 4116",
                "Asna Haroon Khan - Pathologist - 3877",
                "Asna Harroon Khan - Laboratory - 3877",
                "Assessment Room - G10 Hospital - 7429",
                "Assistant Consultant Office - I - Operative Rooms E2 & F5 - 4373",
                "Assistant Consultant Office - II - Operative Rooms E2 & F6 - 4372",
                "Assistant Consultant Office - III - Operative Rooms E2 & F7 - 4371",
                "Associate Consultant Office - Operative Rooms E2 & F8 - 4370",
                "Athar Khawaja - Urologist - 3461",
                "Athar Niaz Rana - Allergy & Immunologist - 4400",
                "Atif Jamal Ahmed - Tameer e Millat Foundation - 3391",
                "Atif Khan - Operative Rooms E2 & F9 - 3242",
                "Atif Rana - Radiologist - 3030",
                "Atif Rana - Radiology - 3030",
                "Attiq ur Rehman - Opd Administration - 3125",
                "Ayaz Khan - Urologist - 3706",
                "Ayesha Akram - Nursing - 3676",
                "Ayesha Junaid - Hematologist - 3820",
                "Ayesha Junaid - Laboratory - 3820",
                "Ayisha Kausar - Opthalmologist - 3766",
                "Azhar Saeed - Neurologist - 3524",
                "Azher Najmi - Human Resource - 3085",
                "Aziz Ahmed Jaan - Administration - 4000",
                "Aziz Ahmed Jan - Executive Management - 4000",
                "Aziz ur Rashid - Opd Administration - 3449",
                "Azra Batool  - Obstetrician Gynecologist - 3479",
                "B2 Floor - Medical Officer Room - 3261",
                "B2 Floor - Nursing Station - 3260/3263",
                "B2 Floor - Reception - 3262",
                "B3 Floor - Nursing Station - 3272/3273",
                "B3 Floor - Room  1 A - 3277",
                "B3 Floor - Room  10 A - 3288",
                "B3 Floor - Room  10 B - 3289",
                "B3 Floor - Room  11 A - 3290",
                "B3 Floor - Room  11 B - 3291",
                "B3 Floor - Room  12 A - 3223",
                "B3 Floor - Room  12 B - 3293",
                "B3 Floor - Room  14 A - 3298",
                "B3 Floor - Room  7 A - 3282",
                "B3 Floor - Room  7 B - 3283",
                "B3 Floor - Room  8 A - 3284",
                "B3 Floor - Room  8 B - 3285",
                "B3 Floor - Room  9 A - 3286",
                "B3 Floor - Room  9 B - 3287",
                "B3 Floor - Ward - 3740",
                "B4 Floor - Medical Officer Room - 3258",
                "B4 Floor - Nursing Station - 3301/3302",
                "B4 Floor - Room  1 A - 3303",
                "B4 Floor - Room  10 A - 3320",
                "B4 Floor - Room  10 B - 3321",
                "B4 Floor - Room  11 A - 3322",
                "B4 Floor - Room  11 B - 3323",
                "B4 Floor - Room  2 A - 3304",
                "B4 Floor - Room  2 B - 3305",
                "B4 Floor - Room  3 A - 3306",
                "B4 Floor - Room  3 B - 3307",
                "B4 Floor - Room  4 A - 3308",
                "B4 Floor - Room  4 B - 3309",
                "B4 Floor - Room  5 A - 3310",
                "B4 Floor - Room  6 A - 3312",
                "B4 Floor - Room  6 B - 3313",
                "B4 Floor - Room  7 A - 3314",
                "B4 Floor - Room  7 B - 3315",
                "B4 Floor - Room  8 A - 3316",
                "B4 Floor - Room  8 B - 3317",
                "B4 Floor - Room  9 A - 3318",
                "B4 Floor - Room  9 B - 3319",
                "Badar Us Salam - ENT Surgeon - 3557",
                "Balqees Yawar - Radiologist - 3044",
                "Barkhurdar Zulfiqar  - Food & Nutrition - 3563",
                "Basharat Ahmad - Tameer e Millat Foundation - 3180",
                "Bashir Ahmed - House Keeping - 3421",
                "Bashir Ahmed - Linen & Laundry - 3216",
                "Basit Rasool - Administration - 3830",
                "Basit Shoaib - MIS - 4239",
                "Belqees Yawar Faiz - Radiology - 3044",
                "C S S D - Operative Rooms B2 - 3956",
                "C S S D - Operative Rooms E2 & F14 - 3086/3778",
                "C S S D - Operative Rooms E3 - 4165",
                "C T F-1 - Radiology - 3727",
                "C T Reporting Room - Radiology - 3723",
                "C T Simulator  - Radiation Oncology - 3445",
                "C T Simulator A-0 - Radiology - 3445",
                "Café 1 Counter - Food & Nutrition - 3032",
                "Café 2 Counter - Food & Nutrition - 3561",
                "Café 4 Counter - Food & Nutrition - 3018",
                "Cardiac Cath Lab - Operative Rooms E2 & F10 - 3089/3627",
                "Cardiac Surgery - Reception - 3457",
                "Cardiology - Cath Lab - 3089/3627",
                "Cardiology - Echo Counter - 3123/4351",
                "Cardiology - Procedure room - 4350",
                "Cardiology - Reception - 3124/3612/4318",
                "Cardiology - Review Room - 3714",
                "Cardiology Clinic - Registration Department - 3871",
                "Cash Counter - Chemotherapy - 3792",
                "Cash Counter A-0 Main Lobby - Registration Department - 3055",
                "Cash Counter A-1 - Registration Department - 3006",
                "Cash Counter B-1 - Registration Department - 3372",
                "Cash Counter Blood Bank - Laboratory - 4345",
                "Cash Counter D-0 - Registration Department - 3630",
                "Cash Counter D-1 - Registration Department - 3812",
                "Cash Counter D-1 ( Lab) - Registration Department - 3241",
                "Cash Counter D-4 ( Lab) - Registration Department - 4345",
                "Chemotherapy Clinic A-3 - Registration Department - 3792",
                "Chief Of Pharmacy - Pharmacy - 3296",
                "Circulation - Shifa Publications - 3441",
                "Complaint Desk - Material Works - 3220",
                "Computer Lab - Medical Staff Affairs - 4076",
                "Conference Room E-4 - Medical Staff Affairs - 3205",
                "Consultant Lounge - Food & Nutrition - 3562",
                "Consultant Lounge - Operative Rooms E3 - 4155",
                "Consultant Lounge Anesthesia - Operative Rooms E2 & F11 - 4364",
                "Consultant Lounge Female E - 2 - Operative Rooms E2 & F12 - 4419",
                "Consultant Lounge Male E - 2 - Operative Rooms E2 & F13 - 3615",
                "Consultant OR - G10 Hospital - 7461",
                "Control Room  G-1 - Security - 3637",
                "Control Room  G-5 - Security - 3448",
                "Control Room Linac I - Radiation Oncology - 3710",
                "Control Room Linac II - Radiation Oncology - 3710",
                "Control Room Simulator - Radiation Oncology - 3102",
                "D2 Floor - D - 2 Nursing - 4191",
                "D2 Floor - D - 2 W-1 (Neuro Step Down unit) - 4186/4189",
                "D2 Floor - D - 2 W-2 (Peads ICU) - 4187/4188",
                "D2 Floor - D - 2 W-3 (Surgical Step Down Unit) - 4184/4185",
                "D2 Floor - D - 2 W-4 (Surgical ICU) - 4182/4183",
                "D2 Floor - M.O Room (Female) - 4192",
                "D2 Floor - M.O Room (Male) - 4194",
                "D2 Floor - SICU-Office - 4195",
                "D2 Floor - Transplant Room 1 - 4197",
                "D2 Floor - Transplant Room 2 - 4198",
                "D2 Floor - Transplant Room 3 - 4113",
                "D2 Floor - Transplant Room 4 - 4339",
                "D2 Floor - Transplant Room 5 - 4340",
                "D2 Floor - Waiting Area - 4190",
                "D3 Floor - Manager Office - 4133",
                "D3 Floor - Reception - 4118",
                "D3 Floor W1 - Reception - 4151/4152",
                "D3 Floor W2 - Room 31 A - 4121/4122",
                "D3 Floor W3 - Nursing Station - 4135/4136",
                "D3 Floor W3 - Room 31 A - 4137",
                "D3 Floor W3 - Room 31 B - 4138",
                "D3 Floor W3 - Room 32 A - 4139",
                "D3 Floor W3 - Room 32 B - 4140",
                "D3 Floor W3 - Room 33  - 4141",
                "D3 Floor W3 - Room 34 - 4142",
                "D3 Floor W3 - Room 35 - 4143",
                "D3 Floor W3 - Room 36 - 4144",
                "D3 Floor W3 - Room 37 - 4145",
                "D3 Floor W3 - Room 38 - 4146",
                "D3 Floor W3 - Room 39 - 4147",
                "D3 Floor W3 - Room 40 - 4148",
                "D3 Floor W4 - Anesthesia M O Room  - 3005",
                "D3 Floor W4 - Nursing station - 4119/4120",
                "D3 Floor W4 - Room 41 - 4123",
                "D3 Floor W4 - Room 42 - 4124",
                "D3 Floor W4 - Room 43 - 4125",
                "D3 Floor W4 - Room 44 - 4126",
                "D3 Floor W4 - Room 45 - 4128",
                "D3 Floor W4 - Room 46 - 4129",
                "D3 Floor W4 - Room 47 - 4130",
                "D3 Floor W4 - Room 48 A - 4131",
                "D3 Floor W4 - Room 48 B - 4132",
                "D3 Floor W4 - Surgical M.O Room (FeMale) - 4178",
                "D3 Floor W4 - Surgical M.O Room (Male) - 4127",
                "Danish Hassan - Clinical Research - 3984",
                "Darakhshan Jabeen - Medical Staff Affairs - 3043",
                "Darakhshan Jabeen - Post Gradutate Medical Education - 3043",
                "Day Care Female A-3 - Chemotherapy - 3836",
                "Day Care Male   A-3 - Chemotherapy - 3702",
                "Dental Clinic Cash Counter - Registration Department - 3885",
                "Dermatology - Reception - 3417/3418",
                "Dermatology Clinic - G10 Hospital - 7438",
                "Dexa Scan - G10 Hospital - 7427",
                "Dialysis Nursing Counter - G10 Hospital - 7409/7447",
                "Dialysis Unit - Reception - 3042/3626",
                "Dialysis Unit - Registration Department - 3042",
                "Dictation Room - Medical Records - 3206",
                "Diesel Room - Material Works - 4311",
                "Dietary Office - Food & Nutrition - 3163 / 3357",
                "Distribution - Operative Rooms B2 - 3142",
                "Distribution - Operative Rooms E3 - 4166",
                "Doctor - Oncall Anesthesia - 13005",
                "Doctor - Oncall Cardiology - 13854",
                "Doctor - Oncall Medicine Unit 1 - 13585",
                "Doctor - Oncall Medicine Unit 2 - 13730",
                "Doctor - Oncall Neurosugery - 14192",
                "Doctor - Oncall Obs Gynae - 13553",
                "Doctor - Oncall Orthopedics - 14127",
                "Doctor - Oncall Paeds - 13331",
                "Doctor - Oncall Plastic Surgery - 13443",
                "Doctor - Oncall Surgery Unit 1 - 13678",
                "Doctor - Oncall Surgery Unit 2 - 14178",
                "Doctor - Oncall Urology - 13679",
                "Drivers Room - Transport Office - 3170",
                "Drug Information Services - Pharmacy - 3977",
                "Duty Medical Officer - G10 Hospital - 7420",
                "Duty Supervisor - Food & Nutrition - 4273",
                "E-3 - Admission & Discharge - 4167",
                "E3 Floor Day Care - Nursing Counter - 4168/4169",
                "E4 Floor W1 - Nursing Counter - 3904/3905",
                "E4 Floor W2 - M.O Room - 3882",
                "E4 Floor W2 - M.O Room - 3906",
                "E4 Floor W2 - Manager Office - 3907",
                "E4 Floor W2 - Nursing Counter - 4176/4177",
                "E4 Floor W2 - Room 1 - 3943",
                "E4 Floor W2 - Room 10 - 3914",
                "E4 Floor W2 - Room 11 - 3921",
                "E4 Floor W2 - Room 12 - 3925",
                "E4 Floor W2 - Room 13 - 3882",
                "E4 Floor W2 - Room 14 - 3988",
                "E4 Floor W2 - Room 2 - 3924",
                "E4 Floor W2 - Room 3 - 3922",
                "E4 Floor W2 - Room 4 - 3913",
                "E4 Floor W2 - Room 5 - 3919",
                "E4 Floor W2 - Room 6 - 3920",
                "E4 Floor W2 - Room 7 - 3915",
                "E4 Floor W2 - Room 8 - 3923",
                "E4 Floor W2 - Room 9 - 3910",
                "E4 Floor W2 - Sleep Disorder Lab - 3922/3924",
                "Ehsan Ul Haq - Admission & Discharge - 3155",
                "Ejaz A.Khan - Pediatrician - 3075",
                "Electrical Control Room - G10 Hospital - 7442",
                "Electrical Sub Station A - 0 - Material Works - 3011",
                "Emergency - Abdu Salam Khan - 3009",
                "Emergency - Admission Desk - 3147/3835",
                "Emergency - Ahmad Fawad Ali - 3009",
                "Emergency - Huma Husnain - 4075",
                "Emergency - Junaid Mustafa - 3414",
                "Emergency - Muhammad Hanif - 3831",
                "Emergency - Reception - 3090 / 3010",
                "Emergency - Rizwan - 3845",
                "Emergency - S.Sobya Owais - 4075",
                "Emergency - Shazia Iram - 4271",
                "Emergency/ Safety Hot Line - Security - 4444",
                "Employ Health - Duty Doctor - 3658",
                "Employ Health - Reception - 3690/4280",
                "Endocrinology - Reception - 3433 / 4310",
                "Endocrinology Clinic A-1 - Registration Department - 3433",
                "ENT Clinic - G10 Hospital - 7430",
                "Entrance A-0 - Security - 3051",
                "Entrance A-1 - Security - 3680",
                "Entrance D-1 - Security - 3669",
                "Entrance Dialysis - Security - 3667",
                "Entrance E-R - Security - 3668",
                "Entrance Foundation - Security - 3153",
                "ER  - Admission & Discharge - 3835/3147",
                "F-3 - Admission & Discharge - 3129/4199/3515",
                "F3 Floor CCU - M.O Room (Cardiology) - 4274",
                "F3 Floor CCU - M.O Room (Cardiology) - 4325",
                "F3 Floor CCU - Main Counter - 4268/4269",
                "F3 Floor CCU - Main Counter - 4308",
                "F-4 - Admission & Discharge - 3096/4353",
                "F4 Floor Bonemarrow Transplant - Nursing Counter - 3389",
                "F4 Floor W1 - Cardiology M O Room - 3855",
                "F4 Floor W1 - Nursing Counter - 3887/3888",
                "F4 Floor W1 - Room 1 A - 3856",
                "F4 Floor W1 - Room 1 B - 3857",
                "F4 Floor W1 - Room 12 - 3947",
                "F4 Floor W1 - Room 13 - 3917",
                "F4 Floor W1 - Room 14 - 3866",
                "F4 Floor W1 - Room 15 - 3869",
                "F4 Floor W1 - Room 16 - 3858",
                "F4 Floor W1 - Room 17 - 3567",
                "F4 Floor W1 - Room 18 - 3886",
                "F4 Floor W1 - Room 2 A - 3858",
                "F4 Floor W1 - Room 2 B - 3859",
                "F4 Floor W1 - Room 3 A - 3860",
                "F4 Floor W1 - Room 3 B - 3861",
                "F4 Floor W1 - Room 4 A - 3862",
                "F4 Floor W1 - Room 4 B - 3863",
                "F4 Floor W1 - Room 5 A - 3864",
                "F4 Floor W1 - Room 5 B - 3865",
                "F4 Floor W1 - Room 6 A - 3912",
                "F4 Floor W1 - Room 6 B - 4294",
                "F4 Floor W1 - Room 7 A - 3946",
                "F4 Floor W1 - Room 7 B - 4293",
                "F4 Floor W2 - Nursing Counter - 3936/4265",
                "F4 Floor W2 - Room 19 A - 3889",
                "F4 Floor W2 - Room 19 B - 3979",
                "F4 Floor W2 - Room 20 A - 3891",
                "F4 Floor W2 - Room 20 B - 3892",
                "F4 Floor W2 - Room 21 A - 3893",
                "F4 Floor W2 - Room 21 B - 3894",
                "F4 Floor W2 - Room 22 A - 3895",
                "F4 Floor W2 - Room 22 B - 3896",
                "F4 Floor W2 - Room 23 A - 3897",
                "F4 Floor W2 - Room 23 B - 3898",
                "F4 Floor W2 - Room 24 A - 3899",
                "F4 Floor W2 - Room 24 B - 3980",
                "F4 Floor W2 - Room 35 - 3935",
                "F4 Floor W2 - Room 36 - 3938",
                "F4 Floor W2 - Room 37 - 3939",
                "F4 Floor W2 - Room 38 - 3940",
                "F4 Floor W3 - Medical Officer Room - 3854",
                "F4 Floor W3 - Nursing Station - 3937/4264",
                "F4 Floor W3 - Room 24 A - 3899",
                "F4 Floor W3 - Room 24 B - 3980",
                "F4 Floor W3 - Room 25 - 3933",
                "F4 Floor W3 - Room 26 - 3932",
                "F4 Floor W3 - Room 27 - 3908",
                "F4 Floor W3 - Room 28 - 3916",
                "F4 Floor W3 - Room 29 - 3926",
                "F4 Floor W3 - Room 30 - 3923",
                "F4 Floor W3 - Room 31 - 3930",
                "F4 Floor W3 - Room 32 - 3931",
                "F4 Floor W3 - Room 33 - 3901",
                "F4 Floor W3 - Room 34 - 3934",
                "F4 Floor W3 - Room 39 - 3911",
                "Faisal Aziz Sandeela - Pharmacy - 3363",
                "Faisal Mehmood - Accounts & Finance - 4317",
                "Faisal Nawaz Khan - Accounts & Finance - 4083",
                "Faisal Saud Dar - Liver Transplant surgeon - 3950",
                "Faiza Ameer - Medical Staff Affairs - 3413",
                "Faiza Badar - Rehabilitation Centre - 3436",
                "Faiza Riaz - Accounts & Finance - 3736",
                "Faizan Ahmed - Urologist - 3021",
                "Farah Naz Mehdi - Accounts & Finance - 3189",
                "Fareed Ullah Khan - Cardiac Surgeon - 3160",
                "Farhan Jilani  - Pharmacy - 3033",
                "Farooq Afzal - Ophthalmologist  - 3338",
                "Farooq Umer  - Accounts & Finance - 3844",
                "Farrukh Mateen - Neurologist - 3743",
                "Farrukh Mateen - Shifa Institute of Medical Technology - 3743",
                "Farzana Shafqat - Gastroenterologist - 3454",
                "Fazal Ilahi - Laboratory - 3064",
                "Fazal Ilahi - Pathologist - 3064",
                "File Review Office - Medical Records - 4260",
                "Finance - G10 Hospital - 7443",
                "Fluroscopy  - Radiology - 3731",
                "Fouzia Abbasi - MIS - 4278",
                "G1 Floor - M.O Room (Gastro ) - 3659",
                "G1 Floor - M.O Room (Surgery) - 3678",
                "G1 Floor - M.O Room (Urology) - 3679",
                "G1 Floor - Main Reception - 3661",
                "G1 Floor - Manager Room - 3676",
                "G1 Floor - Wing - I  Nursing Station - 3662/3842",
                "G1 Floor - Wing - II Nursing Station - 3664/3665",
                "G1 Floor - Wing - III Nursing Station - 3670/3671",
                "G1 Floor - Wing - IV Nursing Station - 3672/3673",
                "G2 Floor - Assistant Consultant (MICU) - 3401",
                "G3 Floor - M.O (Surgical Female) - 3443",
                "G3 Floor - M.O Room - 3490",
                "G3 Floor - M.O Room - 3491",
                "G3 Floor - M.O Room - 3501",
                "G3 Floor - M.O Room - 3504",
                "G3 Floor - M.O Room (Peads Female) - 3331",
                "G3 Floor - Manager Office - 3500",
                "G3 Floor - Nursing Station - 3252/3253",
                "G3 Floor - Nursing Station - 3498/3499",
                "G3 Floor - Wing  - II ( Female Medical Ward ) - 3488/3489",
                "G3 Floor - Wing - I (Male Medical Ward) - 3494/3495",
                "G3 Floor - Wing - III ( Medical I C U) - 3496/3497",
                "G3 Floor - Wing - IV (Medical Step Down ) - 3486/3487",
                "G3 Floor W1 - Duty Doctor Room - 3553",
                "G3 Floor W1 - Nursing Station - 3250/3251",
                "G3 Floor W1 - Room  1 - 3530",
                "G3 Floor W1 - Room  10 A - 3547",
                "G3 Floor W1 - Room  10 B - 3548",
                "G3 Floor W1 - Room  11 A - 3549",
                "G3 Floor W1 - Room  11 B - 3550",
                "G3 Floor W1 - Room  12 - 3552",
                "G3 Floor W1 - Room  2 A - 3531",
                "G3 Floor W1 - Room  2 B - 4250",
                "G3 Floor W1 - Room  3 A - 3533",
                "G3 Floor W1 - Room  3 B - 4252",
                "G3 Floor W1 - Room  4 A - 3535",
                "G3 Floor W1 - Room  4 B - 4253",
                "G3 Floor W1 - Room  5 A - 3537",
                "G3 Floor W1 - Room  5 B - 3538",
                "G3 Floor W1 - Room  6 A - 3539",
                "G3 Floor W1 - Room  6 B - 3540",
                "G3 Floor W1 - Room  7 A - 3541",
                "G3 Floor W1 - Room  7 B - 3542",
                "G3 Floor W1 - Room  8 A - 3543",
                "G3 Floor W1 - Room  8 B - 3544",
                "G3 Floor W1 - Room  9 A - 3545",
                "G3 Floor W1 - Room  9 B - 4254",
                "G3 Floor W2 - Nursing Station - 3247/3254",
                "G3 Floor W2 - Peads  M.O Room (Male) - 3527",
                "G3 Floor W2 - Room  13 - 3505",
                "G3 Floor W2 - Room  14 A - 3506",
                "G3 Floor W2 - Room  14 B - 3474",
                "G3 Floor W2 - Room  15 A - 3526",
                "G3 Floor W2 - Room  15 B - 4257",
                "G3 Floor W2 - Room  16 A - 3325",
                "G3 Floor W2 - Room  16 B - 4258",
                "G3 Floor W2 - Room  17  Private - 3324",
                "G3 Floor W2 - Room  18 A - 3243",
                "G3 Floor W2 - Room  18 B - 3246",
                "G3 Floor W2 - Room  19 A - 3239",
                "G3 Floor W2 - Room  19 B - 3240",
                "G3 Floor W2 - Room  20 A - 3237",
                "G3 Floor W2 - Room  20 B - 3408",
                "G3 Floor W2 - Room  21 A - 3222",
                "G3 Floor W2 - Room  21 B - 3235",
                "G3 Floor W2 - Room  22 A - 3210",
                "G3 Floor W2 - Room  22 B - 3191",
                "G3 Floor W2 - Room  23 A - 3082",
                "G3 Floor W2 - Room  23 B - 3099",
                "G3 Floor W2 - Room  24 - 3146",
                "G3 Floor W2 - Surgry M.O Room(Female) - 3443",
                "G4 Floor W1 - Duty Doctor Room (Medicine) - 3730",
                "G4 Floor W1 - Main Counter - 3565/3566",
                "G4 Floor W1 - Nursing Station W-1 - 3567/3568",
                "G4 Floor W1 - Room  1 - 3586",
                "G4 Floor W1 - Room  10 A - 4246",
                "G4 Floor W1 - Room  10 B - 3595",
                "G4 Floor W1 - Room  11 A - 4247",
                "G4 Floor W1 - Room  11 B - 3596",
                "G4 Floor W1 - Room  12 - 3597",
                "G4 Floor W1 - Room  2 A - 3587",
                "G4 Floor W1 - Room  2 B - 4251",
                "G4 Floor W1 - Room  3 A - 4244",
                "G4 Floor W1 - Room  3 B - 3588",
                "G4 Floor W1 - Room  4 A - 4249",
                "G4 Floor W1 - Room  4 B - 3589",
                "G4 Floor W1 - Room  5 A - 3432",
                "G4 Floor W1 - Room  5 B - 3590",
                "G4 Floor W1 - Room  6 A - 4245",
                "G4 Floor W1 - Room  6 B - 3591",
                "G4 Floor W1 - Room  7 A - 3536",
                "G4 Floor W1 - Room  7 B - 3592",
                "G4 Floor W1 - Room  8 A - 3474",
                "G4 Floor W1 - Room  8 B - 3593",
                "G4 Floor W1 - Room  9 A - 3450",
                "G4 Floor W1 - Room  9 B - 3594",
                "G4 Floor W2 - Duty Doctor Room (Medicine) - 3585",
                "G4 Floor W2 - Nursing Station - 3569/3570",
                "G4 Floor W2 - Room  13 - 3582",
                "G4 Floor W2 - Room  14 A - 4248",
                "G4 Floor W2 - Room  14 B - 3581",
                "G4 Floor W2 - Room  15 A - 3249",
                "G4 Floor W2 - Room  15 B - 3634",
                "G4 Floor W2 - Room  16 A - 3534",
                "G4 Floor W2 - Room  16 B - 3579",
                "G4 Floor W2 - Room  17 A - 3551",
                "G4 Floor W2 - Room  17 B - 3578",
                "G4 Floor W2 - Room  18 A - 3532",
                "G4 Floor W2 - Room  18 B - 3577",
                "G4 Floor W2 - Room  19 A - 3546",
                "G4 Floor W2 - Room  19 B - 3576",
                "G4 Floor W2 - Room  20 A - 3548",
                "G4 Floor W2 - Room  20 B - 3575",
                "G4 Floor W2 - Room  21 - 3574",
                "G4 Floor W2 - Room  22 - 3573",
                "G4 Floor W2 - Room  23 A - 4243",
                "G4 Floor W2 - Room  23 B - 3572",
                "G4 Floor W2 - Room  24 - 3571",
                "G4 Floor W2 - Room  25 - 3583",
                "Gas Room - Material Works - 3008",
                "Gastro 1 - Reception - 3065 / 3695",
                "Gastro 2 - Reception - 3642 / 3694",
                "Gate - 1 - Security - 3503",
                "Gate - 2 - Security - 3179",
                "Gate - 5 - Security - 3810",
                "Gate - 7 - Security - 3639",
                "Gate - 9 - Security - 3639",
                "Gate -10 - Security - 3153",
                "General Surgery - Minor OT - 3437",
                "General Surgery - Reception - 3230/3231",
                "Ghazala Mahmood - Obstetrician Gynecologist - 3616",
                "Ghulam Haider Khalid - Pulmonologist  - 3814",
                "Ghulam Siddiq - General Surgeon - 3232",
                "Ghuncha Sammy - Nursing - 3225",
                "Graphic Designers - Shifa Publications - 3340",
                "Ground Floor Clinic - G10 Hospital - 7426",
                "Gulshan Ara Saeed - Obstetrician Gynecologist - 3480",
                "Gyne/OBS Clinic - G10 Hospital - 7436",
                "H M I S - G10 Hospital - 7446",
                "Habib Ur Rahman - Cardiologist - 3002",
                "Habibullah Abbasi - Protocol Affairs - 4164",
                "Haleema Azmat - Shifa Publications - 3949",
                "Hameed Ullah - MIS - 3960",
                "Hamid Ali Nasir - Dental Surgeon - 3269",
                "Hammad Toor - Shifa Foundation - 4289",
                "Hardware Help Desk - MIS - 3332",
                "Harris R Baig - Anesthesiologist - 3092",
                "Haseeb Ullah - Radiation Oncology - 3713",
                "Haseeb Zia - Liver Transplant surgeon - 4163",
                "Hasnain Ahmed - MIS - 3653",
                "Hematology PGs/Residents - Laboratory - 4115",
                "Hina Saeed - Human Resource - 3564",
                "Hina Tahir - Medical Staff Affairs - 4288",
                "Histopathology PGs/Residents - Laboratory - 3877",
                "Hot Line - Radiology - 2222",
                "Hotline - Material Works - 3072",
                "Hubert Haider - Operative Rooms E2 & F15 - 3554",
                "Huma Husnain - Emergency Medicine  - 4075",
                "Huma Tasleem - Obstetrician Gynecologist - 3480",
                "Huma Zaman - Human Resource - 4300",
                "Humaira Nasir - Laboratory - 3350",
                "Humaira Nasir - Pathologist - 3350",
                "Hussan abbas - Medical Staff Affairs - 4063",
                "Huzaifa Mehtab - Pharmacy - 3195",
                "I P D Nursing Counter - G10 Hospital - 7410/7411",
                "Iffat F.Zaman - Pediatrician - 3364",
                "Ijaz Ahmad - Laboratory - 3640",
                "Ijaz Ahmed - Pathologist - 3640",
                "Ijaz Hussain  - Urologist Peads - 3675",
                "Imaad UR Rehman - Radiologist - 3311",
                "Imaad Ur Rehman - Radiology - 3311",
                "Imran Ali - MIS - 3355",
                "Imran Basheer - Shifa Foundation - 3460",
                "Imran Farooqi - Pathology Services - 4284",
                "Imran Farooqi - Security Services - 4284",
                "Imran Farooqi - Transport Services - 4284",
                "Imran Khalid  - Medical Staff Affairs - 3435",
                "Imran Nabi - Human Resource - 3609",
                "Imran Nazir - Laboratory - 3738",
                "Imran Nazir - Pathologist - 3738",
                "Imran Nomi - Accounts & Finance - 3189",
                "Imran Ullah - MIS - 4232",
                "Imtiaz Ahmed - Dental Surgeon - 3269",
                "Inayat Ullah Khan - Neuro Surgeon - 3186",
                "Internal Medical Clinic - G10 Hospital - 7428",
                "Interventional Radiology - Radiology - 4069",
                "Iram Shakir - Medical Specialist - 3375",
                "Irfan Barkat - Quality Management - 4355",
                "Irfan Barkat - Shifa Foundation - 4355",
                "Irum Iqbal - Medical Staff Affairs - 3075",
                "Javed Yar Khan - MIS - 3466",
                "Javeria Gulzar - Clinical Research - 3985",
                "Junaid Mustafa - Emergency Medicine  - 3414",
                "K H Mujtaba Quadri - Nephrologist - 4415",
                "Kaleem Ullah Toori - Pulmonologist  - 3431",
                "Kalsoom Ramzan - Nursing - 4191",
                "Kamal Ahmed Khan - Distribution - 3973",
                "Kamran Majeed - Urologist - 3427",
                "Kamran Mohiuddin - Shifa Foundation - 4332",
                "Kamran Rashid - Medical Oncologist - 3611",
                "Kamran Tariq - Accounts & Finance - 3029",
                "Kashif Anwar - Human Resource - 3711",
                "Keys Room - Security - 3228",
                "Khaula Ashraf Chowdary - Physiatrist - 4240",
                "Khaula Ashraf Chowdary - Rehabilitation Centre - 4240",
                "Khaula Ijaz - Protocol Affairs - 4164",
                "Khawaja Kashif Taskeen - Radiology - 3729",
                "Khawar Gul Abbasi - Food & Nutrition - 4273/3563",
                "Khawja Sayeed Ahmed - Neurologist - 3004",
                "Khurshid S.Raja - Obstetrician Gynecologist - 3245",
                "Kinza Waqar - Clinical Research - 3985",
                "Laboratory Biochemistry - Laboratory - 3061/4285",
                "Laboratory ER - Laboratory - 4112",
                "Laboratory Hematology - Laboratory - 3335/4287",
                "Laboratory Histopathology - Laboratory - 3215/4286",
                "Laboratory Immunology - Laboratory - 3807",
                "Laboratory Microbiology - Laboratory - 3063/3381",
                "Laboratory Molecular - Laboratory - 3971",
                "Labour Room - G10 Hospital - 7460",
                "Lift Room A Block - Material Works - 3800",
                "Lift Room B & G Block - Material Works - 4179",
                "Lift Room D Block - Material Works - 4180",
                "Lift Room F Block - Material Works - 3801",
                "Linen Room (B - 4) - Linen & Laundry - 3470",
                "Linen Room/Uniform/Tailor Room - Linen & Laundry - 3216",
                "Liver Transplant - Reception - 3846/3173/4416",
                "LPP - G10 Hospital - 7425",
                "Lubna Sohail - Food and Nutrition Services, Housekeeping, IPD, Laundry - 4344",
                "M A Hashmi - General Surgeon - 3234",
                "M P Qazi - Obstetrician Gynecologist - 3229",
                "M R I (Close) - Radiology - 3519",
                "M R I (Open) - Radiology - 3122",
                "M R I Reporting Room - Radiology - 3725",
                "M Salman Rafique - Radiologist - 3311",
                "M.Arsalan - Quality Management - 3992",
                "M.Saleem Khan - Medical Staff Affairs - 4301",
                "M.Salman Rafique - Radiology - 3311",
                "Mahmood Haider Javaid - Infectious Diseases - 3012",
                "Mahmud Majeed - Medical Specialist - 3238",
                "Mahpara Rashid - Human Resource - 4300",
                "Maimoona Siddiqui - Neurologist - 3025",
                "Main Kitchen - Food & Nutrition - 3045",
                "Maintenance - G10 Hospital - 7441",
                "Malik Imad Khan  - Out Patient Services - 4217",
                "Malik Muhammad Uzair - Human Resource - 3346",
                "Malik Muhammad Uzair - Human Resource Services - 3346",
                "Malik Muhammad Uzair - Radiology Services - 3346",
                "Malik Waqas - Accounts & Finance - 4085",
                "Mamoon Rashid - Plastic Surgeon - 3747",
                "Manager Room - Operative Rooms E3 - 4154",
                "Manager/MOs&PGs Lounge - Food & Nutrition - 4333",
                "Manzoor H. Qazi - Executive Management - 3199",
                "Maria Tabbsum - Quality Management - 3992",
                "Marium Tufail - Medical Staff Affairs - 4063",
                "Masood Khan - Pediatrician - 3708",
                "Masooma Saeed - Anesthesiologist - 4367",
                "Masooma Saeed - Operative Rooms E2 & F16 - 4367",
                "Mati Ur Rahman - Pulmonologist / Critical Care - 3431",
                "Mazhar Ali Mufti - Medical Specialist - 3097",
                "Mazhar Hussain Raja - Pediatrician - 3965",
                "Mazhar Jamal Khan - Security - 3600/3300",
                "Medical 1 - Reception - 3641/3196/3718",
                "Medical 2 - Reception - 3821/3825",
                "Medical Gas Room - 2   (Near Gate -10) - Material Works - 4270",
                "Medical Gases - G10 Hospital - 7440",
                "Medical ICU - Duty Doctor Room - 3490",
                "Medical ICU - Duty Doctor Room - 3491",
                "Medical ICU - Duty Doctor Room - 3501",
                "Medical ICU - Duty Doctor Room - 3504",
                "Medical ICU - Reception - 3498/3499",
                "Medical ICU - Wing -I G-2 Male ward Medicine - 3494/3495",
                "Medical ICU - Wing -II G-2 Female Ward - 3488/3489",
                "Medical ICU - Wing -III G-2 MICU - 3496/3497",
                "Medical ICU - Wing -Iv G-2 MICU (SD) - 3486/3487",
                "Medical Transcription - Medical Records - 3613",
                "Medical Transcriptionist - Radiology - 3036",
                "Medical-1 Clinic D-1 - Registration Department - 4181",
                "Mehmood Ahmed Mirza - Marketing Services - 3367",
                "Mehmood Ahmed Mirza - Media Services - 3367",
                "Mehmood Ahmed Mirza - Strategic Planning Services - 3367",
                "Mian Amjad Sohail - Executive Management - 3951",
                "Mian Amjad Sohail - Medical Specialist - 3059",
                "Mian Amjad Sohail - Medical Staff Affairs - 3951",
                "Mian Khalid Akbar - Urologist - 3412",
                "Mobeen Iqbal - Pulmonologist / Critical Care - 3633",
                "Mohammad Amir - General Surgeon - 3475",
                "Mohammad Aslam  - Credit Business & Revenue Management - 3069",
                "Mohammad Irfan - Accounts & Finance - 3347",
                "Mohammad Irshad - MIS - 3332",
                "Mohammad Javed - Library - 3330",
                "Mohammad Kashif Khan - Rehabilitation Centre - 3839",
                "Mohammad Mumtaz - Transport Office - 3071",
                "Mohammad Saeed Khan - Nursing - 3183",
                "Mohammad Salim Khan - Radiation Oncologist - 3201",
                "Mohammad Walayat - Tameer e Millat Foundation - 3391",
                "Mould Room - Radiation Oncology - 3014",
                "Muazzam Hafeez Ansari - MIS - 3143",
                "Muhammad Abdul Azeem - Cardiologist - 3483",
                "Muhammad Ahsan Hussain - Management Information Services  - 3351",
                "Muhammad Ahsan Hussain - MIS - 3351",
                "Muhammad Ali Afridi - Radiation Oncologist - 3037",
                "Muhammad Amjad - Neurologist - 3828",
                "Muhammad Ashraf - Anesthesiologist - 4368",
                "Muhammad Ashraf - Medical Specialist - 4074",
                "Muhammad Ashraf - Operative Rooms E2 & F17 - 4368",
                "Muhammad Asif - Radiology - 3720",
                "Muhammad Aslam Chohan - Risk Management - 3211",
                "Muhammad Bin Tariq - Human Resource - 4309",
                "Muhammad Fahim Islam - Accounts & Finance - 3989",
                "Muhammad Farrukh - Radiation Oncologist - 3280",
                "Muhammad Habib - Psychiatrist - 3620",
                "Muhammad Hanif - Nursing - 3831",
                "Muhammad Ibrahim - Plastic Surgeon - 3997",
                "Muhammad Iqbal - Laboratory - 4114",
                "Muhammad Javid - Nursing - 4133",
                "Muhammad Nadeem - MIS - 4091",
                "Muhammad Naeem - Evening Duty Officer - 3845",
                "Muhammad Naseer - Gastroenterologist - 3502",
                "Muhammad Nasir Ayub - Anesthesiologist - 4369",
                "Muhammad Nasir Ayub - Operative Rooms E2 & F18 - 4369",
                "Muhammad Rafiq  - Accounts & Finance - 4070",
                "Muhammad Salih - Gastroenterologist - 3966",
                "Muhammad Shafqat Iqbal - MIS - 4090",
                "Muhammad Shehnaz - Opd Administration - 3998",
                "Muhammad Shoaib - Accounts & Finance - 3989",
                "Muhammad Umer Amin - Radiology - 3723",
                "Muhammad Usman - Laboratory - 4283",
                "Muhammad Usman - Pathologist - 4283",
                "Muhammad Waseem Awan - Radiology - 3731",
                "Muhammad Yousaf Awan - Medical Specialist - 4220",
                "Muhammad Zameer - Operative Rooms E2 & F19 - 4368",
                "Muhmmad Azher Sheikh - Dental Surgeon - 3269",
                "Mujtaba Quadri - Clinical Research - 4415",
                "Mukhtar Hussain - Accounts & Finance - 3712",
                "Munir Malik - Pediatrician - 3101",
                "Musab Riaz - Radiologist - 3311",
                "Musab Riaz - Radiology - 4078",
                "Musarrat Hussain - Pediatrician - 3295",
                "Mussadiq Khan - General Surgeon - 3803",
                "Nabeegh Arshad - Human Resource - 4300",
                "Nabeel Ahmed - MIS - 4094",
                "Nabeel Anwer - Nursing - 3702",
                "Nabeela Batool - Medical Staff Affairs - 3342",
                "Nabeela Shaheen - Operative Rooms E2 & F20 - 3093",
                "Nabia Tariq - Obstetrician Gynecologist - 3202",
                "Nadia Aman - Dental Surgeon - 3269",
                "Nadia Mehboob - Shifa Institute of Medical Technology - 3580",
                "Nadia Saeed - Medical Specialist - 4074",
                "Nadira Mamoon - Laboratory - 3873",
                "Naeem Akhter - Accounts & Finance - 4317",
                "Naheed Gul - Medical Specialist - 3059",
                "Nasim Yusuf - Endocrinologist - 3271",
                "Nasir Khan - General Surgeon - 4324",
                "Nasir Khan - Opd Administration - 4117",
                "Nasir Khokhar - Gastroenterologist - 3178",
                "Nazia Aziz - Psychologist - 3271",
                "Neonatal ICU - Level – II - 3281",
                "Neonatal ICU - Reception - 3266/3154",
                "Nephrology - Reception - 3007 / 3621",
                "Nephrology Clinic  - Registration Department - 3007",
                "Nephrology Clinic - G10 Hospital - 7424",
                "Network/Data  Help Desk - MIS - 3333",
                "Neurology - Electro Encephalo Gyam - 3744",
                "Neurology - Nerve conduction Study - 3744",
                "Neurology - Neuro Library - 3366",
                "Neurology - Reception - 3175 / 3354",
                "Neurology Clinic - Registration Department - 3175",
                "Neurophysiology Clinic - Registration Department - 3744",
                "Neurosurgery - Reception - 3230 / 3231",
                "New Sub Station (Green Area) - Material Works - 4313",
                "Nimrah Saeed Kiyani - Quality Management - 3638",
                "Nisar Ahmed - Medical Staff Affairs - 3957",
                "Noeen Arshad - Dental Surgeon - 3269",
                "Noor-Ul-Ain - Shifa Institute of Medical Technology - 3983",
                "Nuclear Medicine - Radiology - 3733",
                "Nusrat Yar Khan - Liver Transplant Surgeon - 4417",
                "Nuzhat Sultana - Nursing Education - 3058",
                "Nuzhat Sultana - Nursing Education Services - 3058",
                "O P D Reception - G10 Hospital - 7406/7407",
                "Obs/Gynae - Reception - 3209 / 3327/3423",
                "On Call Consultant Room - Operative Rooms E2 & F21 - 4374",
                "On Call Doctors Room - Operative Rooms E2 & F22 - 4375",
                "Oncology - Reception - 3073 / 3660",
                "Oncology Clinic A-0 - Registration Department - 3660",
                "Operator Console - G10 Hospital - 7400",
                "Opthalmology - Reception - 3091/3167",
                "Opthalomogy Clinic A-0 - Registration Department - 3167",
                "Orthopedic Clinic D-1 - Registration Department - 3150",
                "Orthopedics - Reception - 3080 / 3150",
                "Osama Ishtiaq - Endocrinologist - 3077",
                "P G Room On Call - Radiology - 3311",
                "Panel Approval Counter A-0 - Admission & Discharge - 3159",
                "Panel Billing Counter      A-0 - Admission & Discharge - 4062",
                "Patient Holding Room - Radiation Oncology - 3014",
                "Peads Clinic - G10 Hospital - 7435",
                "Pediatric Medicine - Confrence Room - 4411",
                "Pediatric Medicine - Reception Blue - 3076/4413",
                "Pediatric Medicine - Reception Green - 3256/4412",
                "Pharmacy - G10 Hospital - 7417",
                "Pharmacy Ambulatory A-0 - Pharmacy - 3033",
                "Pharmacy Ambulatory C-0 - Pharmacy - 3556",
                "Pharmacy Ambulatory D-1 - Pharmacy - 3816",
                "Pharmacy Clinical Services - Pharmacy - 3492",
                "Pharmacy Emergency - Pharmacy - 3833",
                "Pharmacy H-0 - Pharmacy - 3015/3017",
                "Pharmacy Oncology A-3 - Pharmacy - 3976",
                "Pharmacy Operation Room H-2 - Pharmacy - 4393",
                "Pharmacy Satellite B-4 - Pharmacy - 3748/3809",
                "Pharmacy Satellite D-3 - Pharmacy - 4150",
                "Pharmacy Satellite G-2 - Pharmacy - 3799",
                "Pharmacy Warehouse - Pharmacy - 3016/3978",
                "Phlebotomy D-1 - Laboratory - 3813",
                "Phlebotomy InPatient (Central Processing Unit) - Laboratory - 3739",
                "Plastic Surgery Clinic - Registration Department - 3417",
                "Post Operative Unit - Operative Rooms E2 & F23 - 4360/4361",
                "Power House - 1 - Material Works - 3048",
                "Power House - 2 - Material Works - 3100",
                "Power House - 3 - Material Works - 3455",
                "Pre Operative - Operative Rooms E3 - 4158",
                "Pre Operative Unit - Operative Rooms E2 & F24 - 4362/4363",
                "Procurement - G10 Hospital - 7459",
                "Psychiatry - Reception - 3518 / 3584",
                "Pulmonolgy - Reception - 3012 / 3083",
                "Pulmonology Clinic - G10 Hospital - 7437",
                "Qaisar Mumtaz - Protocol Affairs - 4164",
                "Qamar Hafeez Kiani - General Surgeon - 3996",
                "Rabia Tabassum - Admission & Discharge - 4088",
                "Radiation Oncology - Reception - 3657",
                "Radiation Oncology Clinic - Registration Department - 3067",
                "Radiologist Room - Radiology - 3311",
                "Radiology Cash Counter F-1 - Registration Department - 4099",
                "Radiology Record - Radiology - 3259",
                "Raheela Aqeel - Radiologist - 3311",
                "Raheela Khatoon - Radiology - 3044",
                "Raisa Kausar - Nursing - 3907",
                "Raja Dawood Ahmed - Accounts & Finance - 3969",
                "Raja Farhat Shoaib - Neurologist - 3827",
                "Rakshanda Khizar - Radiology - 3728",
                "Rao Suhail - Neurologist - 3827",
                "Rasheed Ahmed Chaudhry  - Dermatologist - 3074",
                "Rashid Javed - Accounts & Finance - 4083",
                "Rashid Nazir - Radiologist - 4079",
                "Rashid Nazir - Radiology - 3723",
                "Rashid Quddus - Tameer e Millat Foundation - 3391",
                "Rashid Rasheed - MIS - 4297",
                "Raza Ur Rehman - Human Resource - 3047",
                "Reception - G10 Hospital - 051-2352983/2352990/2352984/",
                "Reception - G10 Hospital - 7404",
                "Reception - House Keeping - 3013/3421",
                "Reception - Lithotripsy - 3656",
                "Reception - Medical Records - 3049/3618",
                "Reception - Nursing Education Services - 3081/3610",
                "Reception - Opd Administration - 3749",
                "Reception - Operative Rooms E2 & F2 - 3092/3094/3095",
                "Reception - Operative Rooms E2 & F3 - 3274",
                "Reception - Operative Rooms E3 - 4160/4170",
                "Reception - Radiation Oncology - 3067",
                "Reception - Radiology - 3026",
                "Reception - Rehabilitation Centre - 3088/3853",
                "Reception A-0 - Laboratory - 3334",
                "Reception B-2 - Operative Rooms B2 - 3704",
                "Reception D-4 - Laboratory - 4414",
                "Reception D-4 Blood Bank - Laboratory - 3126/3837",
                "Reception E-1 - Radiology - 3329/3726",
                "Recovery Room - Operative Rooms B2 - 3438",
                "Recovery Room - Operative Rooms E3 - 4159",
                "Rehabilitation - G10 Hospital - 7463",
                "Rehabilitation Clinic - Registration Department - 3088",
                "Rehana - Medical Staff Affairs - 3957",
                "Rehana Gill - Opd Administration - 4097",
                "Rehana Sayeed - Pediatrician - 3425",
                "Rehna Khizar - Radiology - 3728",
                "Reshma Aziz - Pediatric Surgeon - 5001",
                "Rezzan Khan  - Nutrition And Dietitian - 3339",
                "Rheumatology - Reception - 3821",
                "Rifaqat Ali Jaffri - Radiologist - 4078",
                "Rifaqat Ali Jaffri - Radiology - 4078",
                "Rizwan Taj - Psychiatrist - 3484",
                "Rushqia Mukhtar - Dermatologist - 3851",
                "Ruth Samuel - Infection Control - 3529",
                "Ruth Samuel (MSA) - Nursing - 3529",
                "S Sobya Owais - Emergency Medicine  - 4075",
                "Saad Ur Rehman - Plastic Surgeon - 3456",
                "Saadia Farooq - Ophthalmologist  - 3879",
                "Sadaf Iqbal - Human Resource - 3711",
                "Sadaf Mehboob - Administration - 4218",
                "Saeed Ahmed Mir - Shifa Foundation - 3794",
                "Saeed Akhter - Urologist - 3326",
                "Saeed Ullah Shah - Cardiologist - 3034",
                "Saeed Zamir - Gastroenterologist - 3717",
                "Saeeda Yasmin - General Surgeon - 3221",
                "Sahar Farrukh - Human Resource - 3463",
                "Saima Sattar - Medical Staff Affairs - 3035",
                "Saira Hassan - Medical Oncologist - 3881",
                "Saira Irum - Administration - 3903",
                "Sajjad Hassan Orakzai - Orthopedic Surgeon - 3632",
                "Saleem A. Malik - Plastic Surgeon - 3233",
                "Saleem Khan - Executive Management - 3149",
                "Saleem Siddiqui - Medical Oncologist - 3181",
                "Salman Ahmed Saleem - Pain Management - 4073",
                "Samea K. Ahmad - Tameer e Millat Foundation - 3442",
                "Sameena Ghayur - Laboratory - 3640",
                "Sameena Ghayur - Pathologist - 3640",
                "Samia Hameed - Human Resource - 3874",
                "Samina Ashfaq - Admission & Discharge - 4353",
                "Samina Khurshid - Quality Management - 3200",
                "Samreen Aslam - Radiologist - 3311",
                "Sanam Mustafa - Radiology - 3731",
                "Sanam Somro - Radiologist - 3731",
                "Sanam Yasir - Radiologist - 3731",
                "Sanam Yasir - Radiology - 3731",
                "Sarim Lodhi - ENT Surgeon - 3963",
                "Saud Ali Mustafa - Human Resource - 3047",
                "Secretary Office - Laboratory - 3716",
                "Security main Gate - G10 Hospital - 7456",
                "Sehar Farrukh - Administration - 3463",
                "Shafiq Aslam Awan - Medical Records - 3172",
                "Shafiq Zaman - Shifa Foundation - 3257",
                "Shafqat Ali Hamidani - Pharmacy Services - 3296",
                "Shagufta Rashid - Laboratory - 3353",
                "Shagufta Yasmin - Opd Administration - 3144",
                "Shaheen Ashraf - Obstetrician Gynecologist - 3165",
                "Shaheen M. Mufti - Gastroenterologist - 3070",
                "Shahid Ahmed Shah - Neuro Surgeon - 3823",
                "Shahid Iqbal - Transport Office - 3079",
                "Shahid Javid - Anesthesiologist - 4369",
                "Shahid Javid - Operative Rooms E2 & F25 - 4369",
                "Shahid Khalil - Cardiac Surgeon - 3457",
                "Shahid Khan - MIS - 4282",
                "Shahid Mehmood - Tameer e Millat Foundation - 3180",
                "Shahid Nazir - Pediatrician - 3964/4341",
                "Shahnawaz Khan - House Keeping - 3707",
                "Shaikh Jawaher Ahmed - MIS - 5000",
                "Shaista Ambreen - Rehabilitation Centre - 3214",
                "Shams Ur Rehman Abbasi - Accounts & Finance - 3050",
                "Shawana Kamran - Laboratory - 4326",
                "Shawkat Matabdin - Anesthesiologist - 3098",
                "Shawkat Matabdin - Operative Rooms E2 & F26 - 4367",
                "Shazia Fakhar - Obstetrician Gynecologist - 3608",
                "Shazia Iram - Pediatrician - 4271",
                "Shehla Choudhry - Pediatrician - 3425",
                "Sheraz Alam - Accounts & Finance - 3187",
                "Shift Supervisor  - Nursing - 3115",
                "Shujah Ur Rehman - Accounts & Finance - 3419",
                "Siddique - Shifa Foundation - 4072",
                "Sidra Kiani - Medical Staff Affairs - 4066",
                "Sohail Anjum Awan - Opd Administration - 3104",
                "Sohail Naseem - Pulmonologist / Critical Care - 4314",
                "Sohail-Ur-Raheem Aarbi - Shifa Foundation - 4171",
                "Speech Therapy - Rehabilitation Centre - 3436",
                "Speech Therophy - G10 Hospital - 7462",
                "Staff Room - Rehabilitation Centre - 3024",
                "Sulman Jaffar - Ophthalmologist  - 3434",
                "Sumiya Naqash - Quality Management - 3992",
                "Supervisor Office - Registration Department - 4200/3603",
                "Surgery Clinic - Registration Department - 3872",
                "Syed Afaque Ahmed - Accounts & Finance - 3734",
                "Syed Asim Abbas - Facilities  Management  - 3478",
                "Syed Faizan Alam - Human Resource - 4235",
                "Syed Farhat Abbas - Nephrologist - 3703",
                "Syed M Fawad Sharif - Tameer e Millat Foundation - 3391",
                "Syed Mubbushir Ahmed - Admission & Discharge - 4330",
                "Syed Muhammad Zeeshan - Laboratory - 3473",
                "Syed Muhammad Zeshan  - Microbiologist - 3473",
                "Syed Muneer Hussain - Accounts & Finance - 3193",
                "Syed Muneer Hussain - Executive Management - 3193",
                "Syed Najmul Hassan Shah - Gastroenterologist - 3027",
                "Syed Nayer Mahmud - Nephrologist - 3001",
                "Syed Sajjad Hussain Shah - Accounts & Finance - 3419",
                "Syeda Faiza - Human Resource - 3715",
                "Tahir Aziz - Laboratory - 4348",
                "Tahir Aziz Ahmed - Immunalogist - 4348",
                "Tahir Habib - Medical Staff Affairs - 3342",
                "Tahir Hashmi - Rehmatalogist - 3954",
                "Tahir Hussain - General Surgeon - 3477",
                "Tahir Iqbal - Medical Specialist - 4219",
                "Tahir Mehmood - MIS - 4231",
                "Tahira Mohsin - Nursing - 3500",
                "Taimoor Shah - Quality Management - 3847",
                "Taimoor Shah - Shifa Foundation - 3847",
                "Take Home Services F-3 - Rehabilitation Centre - 4356",
                "Tania Noreen - Medical Staff Affairs - 4301",
                "Tara jaffery - Medical Specialist - 3375",
                "Tariq Hussain - Lithotripsy - 3656",
                "Tariq Karim - Protocol Affairs - 4164",
                "Tariq Naseem - Accounts & Finance - 3876",
                "Tasneem Akhtar - Obstetrician Gynecologist - 3819",
                "Tauqeer Akber - Cardiac Surgeon - 3962",
                "Tauqir A. Shah - Medical Specialist - 3166",
                "Tayyab Badshah - Endocrinologist - 3356",
                "Tayyaba Sadiq - Shifa Institute of Medical Technology - 3983",
                "Treatment Planning Room - Radiation Oncology - 3713",
                "Ultrasound - I - Radiology - 3044",
                "Umair Arif Awan - MIS - 4237",
                "Umar Aftab Awan - MIS - 3815",
                "Umer Ameen - Radiologist - 3731",
                "Urology & Kidney Transplant - Reception - 3038 / 3169",
                "Urology Clinic - G10 Hospital - 7431/7433/7434",
                "Usman Mumtaz - Protocol Affairs - 4164",
                "Uzma Qasim - Radiation Oncologist - 4263",
                "Uzma Tahseen - Medical Specialist - 3954",
                "Wajid Yar Khan - Medical Specialist - 3447",
                "Waqar M. Jan - Orthopedic Surgeon - 3631",
                "Wardah Khurshid - Human Resource - 3359",
                "Waseem Awan - Radiologist - 3731",
                "Waseem Shakir - MIS - 3465",
                "Wasim Tariq - Neurologist - 4109",
                "Water Supply & Pump Room - Material Works - 3020",
                "Wazir Mohammad - Accounts & Finance - 3127",
                "Wazir Muhammad - Accounts & Finance - 3127",
                "Wood Work Shop - Material Works - 3453",
                "X-Ray - G10 Hospital - 7439",
                "Yasir Iqbal - Pediatrician - 3337",
                "Yasmeen Saggu - Nursing - 3204",
                "Yasmin Saggu - Nursing Services - 3204",
                "Yawar Najam - Pediatrician - 3426",
                "Yousaf Chaudhry - Radiologist - 3023",
                "Yousaf Chaudhry - Radiology - 3023",
                "Yousaf Hasan - Cardiologist - 3349",
                "Zafar Ali - Laboratory - 4322",
                "Zafar Iqbal - ENT Surgeon - 3168",
                "Zafar Rabani - ENT Surgeon - 3430",
                "Zafar Ullah - Rheumatologist - 3040",
                "Zahid Alam Siddiqui - Accounts & Finance - 3188",
                "Zahid Ayubi - Shifa Publications - 3440",
                "Zameer - Anesthesiologist - 4368",
                "Zarar Ahmed Butt - MIS - 3352",
                "Zareen Sadaf - Accounts & Finance - 3188",
                "Zeba Ilyas Matin - Ophthalmologist  - 3219",
                "Zeeshan abdul Majeed - Accounts & Finance - 3187",
                "Zeeshan bin Ishtiaque - Quality Assurance - 3902",
                "Zeeshan bin Ishtiaque - Quality Management - 3902",
                "Zeeshan Bin Ishtiaque - Shifa Foundation - 3902",
                "Zeeshan Mehboob - MIS - 4092",
                "Zia A.D - Food & Nutrition - 3268",
                "Zohaib Javed - Medical Staff Affairs - 3103"



        };
        listItems=new ArrayList<>(Arrays.asList(items));
        adapter=new ArrayAdapter<String>(this, R.layout.list_item, R.id.txtitem, listItems);
        listView.setAdapter(adapter);
    }
}